AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 Instance Definition"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b0dcb5067f052a63
      InstanceType:  t2.micro
      Tags:
        - Key: Environment
          Value: dev
        - Key: TaskID
          Value: '1234'
        - Key: Name
          Value: !Join [ " ", [ "Test", "Instance" ] ]
      SecurityGroups:
        - !Ref EC2SecurityGroup
  EC2SecurityGroup:
     Type: AWS::EC2::SecurityGroup
     Properties:
       GroupName: 'ssh-security-group'
       GroupDescription: 'Enable SSH access via port 22'
       SecurityGroupIngress:
         - IpProtocol: tcp
           FromPort: '22'
           ToPort: '22'
           CidrIp: '0.0.0.0/0'
       Tags:
          - Key: Name
            Value: 'ssh-sg'