AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 Instance Definition"

Parameters:
  EC2InstanceTypeParam:
    Type: String
    Default: 't2.micro'
    AllowedValues:
      - 't2.micro'
      - 't1.micro'
    Description: 'EC2 Instance types in Free-tier usage'
  EC2InstanceNameParam:
    Type: String
    Default: 'Test Instance'
    Description: 'Specifies EC2 Instance name'

Mappings:
  RegionAmiIdMap:
    us-east-1:
      AMI: ami-0b0dcb5067f052a63
    eu-central-1:
      AMI: ami-076309742d466ad69

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap ['RegionAmiIdMap', !Ref AWS::Region, 'AMI']
      InstanceType:  !Ref EC2InstanceTypeParam
      Tags:
        - Key: Environment
          Value: dev
        - Key: TaskID
          Value: '1234'
        - Key: Name
          Value: !Ref EC2InstanceNameParam
        - Key: Region
          Value: !Ref AWS::Region

Outputs:
  ServerDns:
    Value: !GetAtt ['EC2Instance', 'PublicDnsName']