AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 Instance Definition"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b0dcb5067f052a63
      InstanceType:  t2.micro
      Tags:
        - Key: Environment
          Value: dev
        - Key: TaskID
          Value: '1234'
        - Key: Name
          Value: 'MyInstance'